# Generated by Django 4.0.5 on 2022-06-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddate',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='adddate',
            name='startdate',
        ),
        migrations.AddField(
            model_name='adddate',
            name='during',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
