# Generated by Django 4.0.5 on 2022-06-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_remove_adddate_enddate_remove_adddate_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('tour_place', models.CharField(max_length=100)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.adddate')),
            ],
        ),
    ]
