# Generated by Django 4.0.5 on 2022-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_alter_adddate_enddate_alter_adddate_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddate',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adddate',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
