# Generated by Django 4.0.5 on 2022-06-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_adddate_enddate_alter_adddate_startdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adddate',
            options={'managed': False},
        ),
    ]
