# Generated by Django 4.0.5 on 2022-06-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_hotplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotplace',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
