# Generated by Django 4.0.5 on 2022-06-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_rename_tour_id_hotplace_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotplace',
            options={'managed': True},
        ),
    ]
