# Generated by Django 4.0.5 on 2022-06-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_alter_adddate_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adddate',
            table='schedule_app_adddate',
        ),
    ]
