# Generated by Django 4.0.5 on 2022-06-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_alter_hotplace_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.adddate'),
        ),
    ]
