# Generated by Django 4.0.5 on 2022-06-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_alter_adddate_table'),
        ('schedule_app', '0005_alter_hotplace_options'),
    ]

    operations = [
    ]
