# Generated by Django 4.0.5 on 2022-06-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_merge_20220621_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adddate',
            options={'managed': True},
        ),
    ]
