# Generated by Django 4.0.5 on 2022-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_alter_hotplace_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='tour_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
