# Generated by Django 4.0.5 on 2022-06-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0007_alter_hotplace_days_alter_hotplace_tour_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotplace',
            options={},
        ),
    ]
