# Generated by Django 4.0.5 on 2022-06-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0007_alter_adddate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adddate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotplace',
            options={},
        ),
        migrations.RemoveField(
            model_name='adddate',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='adddate',
            name='startdate',
        ),
        migrations.AlterModelTable(
            name='adddate',
            table=None,
        ),
    ]
