# Generated by Django 4.0.5 on 2022-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_alter_hotplace_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='place_author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
