# Generated by Django 4.0.5 on 2022-06-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_alter_adddate_options_alter_hotplace_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adddate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hotplace',
            options={'managed': True},
        ),
    ]
