# Generated by Django 4.0.5 on 2022-06-23 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_app', '0009_hotplace_place_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotplace',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='place_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
