# Generated by Django 4.0.5 on 2022-06-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wirte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wirte_id', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Wirte',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='WirteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage_app.wirte')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
            options={
                'db_table': 'WirteItem',
            },
        ),
    ]
