# Generated by Django 4.0.5 on 2022-06-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wirteitem',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='wirteitem',
            name='title',
        ),
        migrations.DeleteModel(
            name='Wirte',
        ),
        migrations.DeleteModel(
            name='WirteItem',
        ),
    ]
