# Generated by Django 4.0.5 on 2022-06-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_author_alter_reply_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
    ]
